# How to author Executors: https://circleci.com/docs/2.0/reusing-config/#authoring-reusable-executors
description: >
  Default executor for deployment jobs
docker:
  - image: 'circleci/python:<<parameters.tag>>'
working_directory: ~/app
parameters:
  tag:
    default: 3
    type: string
